on:
  workflow_dispatch 
jobs:
  exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            var path = require('path');
            const exec = require('child_process').execSync;
            var walk = function(dir, done) {
                var results = [];
                fs.readdir(dir, function(err, list) {
                if (err) return done(err);
                var i = 0;
                (function next() {
                    var file = list[i++];
                    if (!file) return done(null, results);
                    file = path.resolve(dir, file);
                    fs.stat(file, function(err, stat) {
                    if (stat && stat.isDirectory()) {
                        walk(file, function(err, res) {
                        results = results.concat(res);
                        next();
                        });
                    } else {
                        results.push(file);
                        next();
                    }
                    });
                })();
                });
            };
            function compilation(n, files){
                let file = {};
                for(let i in files){
                    let d = fs.readFileSync(files[i], "utf-8");
                    d = Buffer.from(d, 'utf-8').toString('base64');
                    file[i.split("bunker-v1/public/")[1]] = d;
                }
                fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE, "update.js"), JSON.stringify(file));
                exec("git add "+path.join(process.env.GITHUB_WORKSPACE, "update.js"));
                exec("git commit");
                exec("git push");
            }
            walk(path.join(process.env.GITHUB_WORKSPACE, "public"), compilation);
