on:
  workflow_dispatch 
jobs:
  exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const path = require('path')
            console.log("well...?");
            const filenames = fs.readdirSync(process.env.GITHUB_WORKSPACE)
            filenames.forEach(file => {
              console.log(file);
            });
            console.log(process.env.GITHUB_WORKSPACE);
