on:
  workflow_dispatch 
jobs:
  exist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const path = require('path')

            const filenames = fs.readdirSync(
              path.join(process.env.GITHUB_WORKSPACE, 'public')
            )
            filenames.forEach(file => {
              console.log(file);
            });
